config/routes.rb
Rails.application.routes.draw do
  resources :prospects
  resources :coins
  resources :cryptos

  root 'cryptos#index'
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  before_save :downcase_fields
  before_save :remove_comma
  validates :name, presence: true
  validates :qty, presence: true

  def downcase_fields
    self.name.downcase! if self.name?
  end

  def remove_comma
    self.qty.to_s.delete(',').to_f if self.qty
  end

  def self.total_coin(crypto, price)
    total = price.to_f * crypto.qty
    total.to_s
    crypto.update_attributes(total: total)
  end

  def self.value_coin(x, value)
    x.update_attributes(value: value)
  end

  def self.mc_coin(x, price)
    x.update_attributes(mc: price)
  end

  def self.one_coin(x, percent)
    x.update_attributes(one: percent)
  end

  def self.twenty_four_coin(x, percent)
    x.update_attributes(twenty_four: percent)
  end

  def self.btc(prospect, price)
    prospect.update_attributes(btc: price)
  end

  def self.pp_coin(crypto, total)
    crypto.each do |x|
      percent = ((x.total.to_f / total) * 100).round(2)
      percent.to_s
      x.update_attributes(pp: percent)
    end
  end


  def self.link
    url = HTTParty.get("https://api.coinmarketcap.com/v1/ticker/?start=0&limit=1250")
    @result = JSON.parse(url.body)
  end


  def self.market
    url = HTTParty.get("https://api.coinmarketcap.com/v1/global/")
    result = JSON.parse(url.body)
    market = result["total_market_cap_usd"]
    time = result["last_updated"]
    db = Coin.find(1)
    db.update_attributes(global: market, time: time)
  end

  def self.total
    investment = 12360
    crypto = Crypto.all.where.not(name: nil, day: true)
    prospect = Prospect.all
    market
    link
    @price = []
    crypto.each do |c|
      @result.each_with_index do |group,index|
        if (c.name == group["id"] || c.name == group["name"] ||  c.name == group["name"].titleize || c.name == group["symbol"] || c.name == group["symbol"].downcase && !group["name"].include?("[Futures]"))
          @price << c.qty * group["price_usd"].to_f
          total_coin(c, group["price_usd"])
          value_coin(c, group["price_usd"])
          mc_coin(c, group["market_cap_usd"])
          one_coin(c, group["percent_change_1h"])
          twenty_four_coin(c, group["percent_change_24h"])
        end
      end
    end

    prospect.each do |pros|
      @result.each_with_index do |group,index|
        if (pros.name == group["id"] || pros.name == group["name"] ||  pros.name == group["name"].titleize || pros.name == group["symbol"] || pros.name == group["symbol"].downcase && !group["name"].include?("[Futures]"))
          value_coin(pros, group["price_usd"])
          btc(pros, group["price_btc"])
          mc_coin(pros, group["market_cap_usd"])
          one_coin(pros, group["percent_change_1h"])
          twenty_four_coin(pros, group["percent_change_24h"])
        end
      end
    end

    total = @price.sum
    profit = total - investment
    pp_coin(crypto, total)
    dbsave = Coin.find(1)
    dbsave.update_attributes(total: total, profit: profit)
  end



end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:edit, :update, :destroy]
  include CryptosHelper

  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all.where.not(name: nil, day: true).order(:name)
    percentage = Change.last
    @daily = percentage.percentage.to_s
    @prospects = Prospect.all.order(:name)
    coin = Coin.find(1)
    @investment = "$12,360"
    @total = coin.total
    @profit = coin.profit
    @market = coin.global
    @last_update = Time.at(coin.time.to_i).strftime("%I:%M %p")
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
    @crypto = Crypto.find(params[:id])
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)
    respond_to do |format|
      if @crypto.save
        Crypto.total
        format.html { redirect_to cryptos_url, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        Crypto.total
        format.html { redirect_to cryptos_url, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    Crypto.total
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:name, :investment, :qty, :exchange)
    end
end

app/helpers/cryptos_helper.rb
module CryptosHelper

end

app/views/cryptos/_form.html.erb
<%= form_for(@crypto) do |f| %>
  <% if @crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% @crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.text_area :qty %>
  </div>
  <div class="field">
    <%= f.label "Location" %><br>
    <%= f.select :exchange, ["", "Binance", "Bittrex", "Coinbase Alex", "Coinbase Fede", "EtherDelta", "HitBtc", "Kucoin", "Ledger", "Other"] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>ViGo Investment Portfolio </h1>
  <div style="clear: both">
    <h5 style="float: left"></h5>
    <h5 style="float: right"></h5>
  </div>

  <br>
  <div style="clear: both">
    <h3 style="float: left">Market Cap: <%= number_to_currency(@market) %></h3>
    <h3 style="float: right">Total: <%= number_to_currency(@total) %></h3>
  </div>
  <div style="clear: both">
    <h4 style="float: left">Investment: <%= @investment %></h4>
    <h4 style="float: right">Profit: <%= number_to_currency(@profit) %></h4>
  </div>
  <div style="clear: both">
    <h5 style="float: left">Last Day: <%= @daily %>%</h5>
    <h5 style="float: right">Last Updated: <%= @last_update %></h5>
  </div>

  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>Coin</th>
        <th>Total</th>
        <th>Value</th>
        <th>Qty</th>
        <th>MktCap</th>
        <th>Change(1hr)</th>
        <th>Change(24hr)</th>
        <th>% of Portolfio</th>
        <th>Location</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cryptos.each do |crypto| %>
      <tr>
        <td><%= crypto.name.titleize %> </td>
          <td> <%= number_to_currency(crypto.total) %></td>
          <td> $<%= crypto.value %></td>
          <td><%= crypto.qty %> </td>
          <td><%= crypto.mc ? number_to_human(crypto.mc) : "N/A" %> </td>
          <td class="<%= crypto.one.to_f >= 0 ? "green" : "red" %>"> <%= crypto.one ? crypto.one : "0.00" %>%</td>
          <td class="<%= crypto.twenty_four.to_f >= 0 ? "green" : "red" %>"> <%= crypto.twenty_four ? crypto.twenty_four : "0.00" %>%</td>
          <td> <%= crypto.pp %>%</td>
          <td> <%= crypto.exchange %></td>
          <td><%= link_to 'Edit', edit_crypto_path(crypto) %></td>
          <td><%= link_to 'Delete', crypto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Crypto', new_crypto_path %>

  <br>
  <br>
  <hr>


<h2>Coins to watch</h2>
<br>
<%= link_to 'New Coin to Watch', new_prospect_path %>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>Coin</th>
      <th>Price USD</th>
      <th>Price BTC</th>
      <th>MktCap</th>
      <th>Change(1hr)</th>
      <th>Change(24hr)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.name.titleize %> </td>
        <td> $<%= prospect.value %></td>
        <td> <%= prospect.btc %></td>
        <td><%= number_to_human(prospect.mc) %> </td>
        <td class="<%= prospect.one.to_f >= 0 ? "green" : "red" %>"> <%= prospect.one %>%</td>
        <td class="<%= prospect.twenty_four.to_f >= 0 ? "green" : "red" %>"> <%= prospect.twenty_four %>%</td>
        <td><%= link_to 'Delete', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


</div>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crypto.name %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @crypto.qty %>
</p>

<p>
  <strong>Investment:</strong>
  <%= @crypto.investment %>
</p>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %>